### ISSUE TITLE
Unilateral Implant Issue

### ISSUE THREAD

**Issue by akapp** [leaddbs/leaddbs#100]
I was having some issues reconstructing patients who have unilateral implantations. I pushed a quick fix to `ea_manualreconstruction.m` in order to avoid calling the second dimensions of markers etc. in the case that only one side is being reconstructed.

In general, this fix avoids determining laterality. If a person selects `Right Only` or `Left Only` the result is the same. Wondering if you guys have any thoughts on this. Does it matter? Should we make changes so that sidedness is coded into the structure i.e if you choose `Right Only --> Options.sides = 1`  and if you choose `Left Only --> Options.sides = 2`

May not be worth the headache, but a thought worth considering.

**Comment by andreashorn** [comment]
Hi Ari,

Yes, we should bother - right should always be inside the first cell and left in the second - I.e. the options.side needs to be correct.
There are many reasons for this throughout lead DBS..

Best, Andy

**Comment by andreashorn** [comment]
Hi all, 

unfortunately, unilateral leads are not well supported. Would be great to add more support for them at some point (also requested here: http://www.lead-dbs.org/?topic=problems-with-unilateral-electrode-placement).

Best, Andy

**Comment by andreashorn** [comment]
With current version, unilateral leads are at least supported for basic steps (up until visualization).
