### ISSUE TITLE
SPM error using sqrtm - non-finite input

### ISSUE THREAD

**Issue by akapp** [leaddbs/leaddbs#101]
I'm getting the following error when runing SPM12, SPM12 SHOOT and SPM12 DARTEL normalization routines in LEAD DBS:

```
Error using sqrtm (line 35)
Expected input to be finite.

Error in spm_maff8>M2P (line 293)
V  = sqrtm(J*J');

Error in spm_maff8>affreg (line 120)
    sol  = M2P(M);

Error in spm_maff8 (line 26)
[M,ll,h]      = affreg(buf, MG, x, ff, varargin{4:end});

Error in spm_preproc_run>run_job (line 108)
                Affine = spm_maff8(obj.image(1),job.warp.samp,
                obj.fwhm,     tpm,Affine,job.warp.affreg);

Error in spm_preproc_run (line 41)
        varargout{1} = run_job(job);

Error in ea_newseg (line 53)
    spm_preproc_run(job); % run "Segment" in SPM 12 (Old
    "Segment" is now referred to as "Old Segment").

Error in ea_newseg_pt (line 12)
ea_newseg(directory,presentfiles,dartel,options,del,force)

Error in ea_normalize_spmshoot (line 64)
ea_newseg_pt(options,1,1);

Error in ea_autocoord (line 93)
        eval([options.normalize.method,'(options)']); % triggers
        the normalization function and passes the options struct
        to it.

Error in ea_run (line 95)
                    ea_autocoord(options);

Error in lead_dbs>run_button_Callback (line 190)
ea_run('run',options);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in lead_dbs (line 43)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)lead_dbs('run_button_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback
```

It looks like 
```
M =

   NaN   NaN   NaN   NaN
   NaN   NaN   NaN   NaN
   NaN   NaN   NaN   NaN
     0     0     0     1
```

on the second iteration of 

```
spm_preproc_run (v6365)                     13:19:40 - 28/03/2017
========================================================================
Segment /Volumes/subjectid/anat_t1.nii,1
```

Any thoughts on how to fix this?

**Comment by andreashorn** [comment]
Hi Ari,

I heard about this before and it could be related to the fact that we use a custom TPM.
Could you test the segmentation directly out of SPM from that data (which will then use the standard TPM) and see if this fixes the issue?

Best, Andy

**Comment by akapp** [comment]
Yep. Switched to the standard tpm `spm12/tpm/TPM.nii` and it worked fine

**Comment by andreashorn** [comment]
Hi Ari,

could you please – if you find the time – replace your TPM & dartel folder with this one?
https://dl.dropboxusercontent.com/u/18255196/tpm_dartel_replace.zip

Would be great to know if this fixes it.. 
Because our custom TPM shows better STN segmentations at least in preliminary data so could be worth it to stick with it if possible.

Thanks!
Best, Andy

**Comment by andreashorn** [comment]
(Replace TPM and try again from within Lead, not SPM).

**Comment by akapp** [comment]
Hi Andy,

That worked perfectly!  Thank you so much.

**Comment by andreashorn** [comment]
Hi Ari, thanks for testing!

@ningfei we should replace these data files in the release, too (they are the ones I use already since some time, apparently never put them on the server).

Best, Andy

**Comment by ningfei** [comment]
@andreashorn guess you mean replace `TPM_Lorio_Draganski.nii`, right? since other dartel files are not included in the release, they will be generated on user's machine for the first time use.

**Comment by andreashorn** [comment]
Hi Ningfei, sorry, no and yes – forgot files are being generated. So we don't have to replace anything. I didn't change TPM_Lorio_Draganski.nii. Thanks for clarifying. I guess Ari was one of the few users who had an intermediary TPM generated via Github.

**Comment by ningfei** [comment]
okay, cool. kein Problem :)

**Comment by akapp** [comment]
Thank you guys!
