### ISSUE TITLE
Cannot open lead 

### ISSUE THREAD

**Issue by haililihai** [leaddbs/leaddbs#102]
Environment: OS X (10.11) & MATLAB R2016b

I git clone the latest leaddbs and set the path in MATLAB, however, LeadDBS cannot be opened correctly. After input `lead`, nothing but endless written files `ea_prefs_${uid}.m` in the ${earoot}. There is an endless loop for running code (ea_prefs.m, Line 28) `uprefs=feval(uid,patientname);`. How to solve the problem?

**Comment by andreashorn** [comment]
Hi Haililihai,

please read "Installation via Github" in the manual: https://leaddbs.gitbooks.io/leaddbs-manual/content/Installation.html

Simply cloning unfortunately does not work but instead you also need some data files.
Also, you need to have SPM12 on the ML path. Then it should work fine!

**Comment by haililihai** [comment]
Hi Andreas,

Thank you for your instruction, I strictly followed the installation manual, however, the exact same error was showing again. 
```
Operation terminated by user during ea_prefs_5682a65d_4cc9_471c_92b5_fb4de73b7763 (line 17)

In ea_prefs_725e0d45_6aae_4502_86f4_118131572788 (line 28)
    uprefs=feval(uid,patientname);

In ea_prefs_e0c3f869_d95c_4ef3_a3b5_74148b9f5fa5 (line 28)
    uprefs=feval(uid,patientname);

In ea_prefs_da803915_703e_4a5c_922d_0e259d2c84f3 (line 28)
    uprefs=feval(uid,patientname);

In ea_prefs_75d8c9b4_c0c7_4446_ad47_68a5fbcc91dd (line 28)
    uprefs=feval(uid,patientname);

In ea_prefs_a74987ad_c94c_4a75_9ea0_051b775d4b46 (line 28)
    uprefs=feval(uid,patientname);

......

In ea_prefs_98d9ae38_08cf_4a99_be75_8bd9a206e6a0 (line 28)
    uprefs=feval(uid,patientname);

In ea_prefs (line 28)
    uprefs=feval(uid,patientname);

In ea_checkleaddirs (line 2)
prefs=ea_prefs('');

In lead>lead_OpeningFcn (line 79)
ea_checkleaddirs;

In gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

In lead (line 42)
    gui_mainfcn(gui_State, varargin{:});
```
I could not figure it out :(
I will try it on another version of MATLAB or OS, maybe this is a OS-dependent or MATLAB-dependent problem.

**Comment by andreashorn** [comment]
Hi Halilihai,

Maybe get a downloadable version (not git at all) from the website first and try if that one works?

Best, Andy

**Comment by ningfei** [comment]
Hi @haililihai,

Please make sure you have deleted `.ea_prefs.m` and `.ea_prefs.mat` in your home directory, and try again. You can do it by `delete([ea_gethome,'.ea_prefs.m'])` and `delete([ea_gethome,'.ea_prefs.mat'])` in matlab.

Best,
Ningfei

**Comment by haililihai** [comment]
Thanks for your suggestion @ningfei , finally it works! :) 👍

**Comment by ningfei** [comment]
cool :)

**Comment by andreashorn** [comment]
Awesome!
