### ISSUE TITLE
Fix "cutting planes" Matlab bug in >R2015 versions

### ISSUE THREAD

**Issue by andreashorn** [leaddbs/leaddbs#111]
Maybe you've seen this, the anatomy planes are being cut in newer Matlab versions when zooming in (see screenshot). Anyone got a clue why this is happening?
<img width="948" alt="screen shot 2017-07-26 at 6 47 51 pm" src="https://user-images.githubusercontent.com/1291036/28633125-0e2ab862-7233-11e7-8840-c2cdbffb35ac.png">

**Comment by toddherrington** [comment]
Hi Andy,

It relates the axes property ‘clipping’ which should be set to ‘off’

I have included the following lines in my local build of ea_write (after line 46) that zooms in closer to the lead, re-centers the camera pivot point for manual rotation and sets the figure background to black (though I think that is now the default).

    figure(resultfig);
    zoom(4); 
    set(gca,'cameraviewanglemode','manual','clipping','off'); 
    axis('off'); 
    set(gcf,'color','k'); 

Probably should have pushed this at some point, and happy to now if helpful (perhaps without the zoom)… 

Todd

**Comment by andreashorn** [comment]
Awesome, Todd, will add this. It didn't happen in 2015 versions so I never bothered to find out what happens in the newer ones.
