### ISSUE TITLE
Switch backdrops

### ISSUE THREAD

**Issue by andreashorn** [leaddbs/leaddbs#116]
(version 1.6.4.2 of Lead-DBS) During 3D-visualisation in the native space, the backdrop image seems to be fixed to post-op CT, so I cannot switch to pre-op T2W MRI images, even after selecting the “Patient Pre-OP” option in the Anatomy Slices window. Just checking whether I missed something since this repeats for several patients.

also need to reinstate the "choose" image.

**Comment by cboulay** [comment]
I also experienced the same thing. All of my modifications to ea_elvis.m were just to handling key events so I don't think I could have done this, at least I hope note.

**Comment by andreashorn** [comment]
No, am sure we just missed it over the time.. Often things that we don't use much ourselves get lost over the versions, unfortunately.. :(
