### ISSUE TITLE
Images missing from downloads

### ISSUE THREAD

**Issue by neurolabusc** [leaddbs/leaddbs#129]
I have downloaded the full distribution of Lead-DBS from the website (www.lead-dbs.org) as well as from the 'necessary datafiles' link from the project front page. Both are missing the image dartelmni_1.nii..dartelmni_6.nii - these are used by the scripts (e.g. ea_normalize_spmdartel) to compute pairwise co-registration. This is described in the documents https://leaddbs.gitbooks.io/leaddbs-manual/content/Normalization%20of%20Images.html and seems to provide a way for DARTEL without creating a local template. Are these images available, or has this method been abandoned (in which case the scripts and documentation should be updated). It seems like a nice approach for centers that do not have a large population of T1 scans from healthy adults required to generate an in-house template, so I would be sad to see this dropped.

**Comment by andreashorn** [comment]
Hi Chris,

the images are being generated on the first run (just choose a folder with an anat_t1.nii file inside, click normalize, choose Dartel or shoot as method and press run).
Takes a while to generate them on first run.
Currently evaluating the methods for subcortical normalization/segmentation.

Best, Andy
