### ISSUE TITLE
Check reg multiple subjects

### ISSUE THREAD

**Issue by siobhane** [leaddbs/leaddbs#131]
When checking normalisation in multiple subjects at once and clicking e.g. approve or disapprove, when Lead moves on to next subjects header of check reg figure and selected patient does not match:
![screen shot 2017-12-11 at 14 36 59](https://user-images.githubusercontent.com/15309848/33833864-5339bac4-de81-11e7-9d40-32f0cdf12ceb.png)

**Comment by ningfei** [comment]
Hi Siobhan, the `approve`/`disapprove` button goes through different modalities of the same subject. When multiple subjects are selected, there should be mutiple `Check Coregistration` or `Check Normalization` windows popped up.

**Comment by siobhane** [comment]
Hi Ningfei, exactly. The problem is that file name and path do not match. This can easily confuse the user and he could approve or disapprove the wrong subject.
