### ISSUE TITLE
Cannot visualize electrode or calculate VTA for electrode that can be visualised in lead group

### ISSUE THREAD

**Issue by siobhane** [leaddbs/leaddbs#148]
In Lead DBS stops at line 43 in ea_showelectrode 
>>try
        startpoint=trajectory{side}(1,:)-(2*(coords_mm{side}(1,:)-trajectory{side}(1,:)));
    catch
        keyboard
    end<<
 and in lead group when trying to calculate VTA says electrode cannot be visualised. However, in Lead group when this patient is individually selected electrode can be visualised.

**Comment by andreashorn** [comment]
Fixed already.
