### ISSUE TITLE
Export 3D-results fig to PDF

### ISSUE THREAD

**Issue by andreashorn** [leaddbs/leaddbs#16]
We *could* try to export the 3D-results to an interactive PDF via this code here:
http://www.mathworks.com/matlabcentral/fileexchange/37640-export-figure-to-3d-interactive-pdf

I still think that this would be a quite messy thing to try/do. Highly optional!

**Comment by ningfei** [comment]
Need to do more study on this. The pdf is cool, but the code here is not very well maintained.

**Comment by andreashorn** [comment]
Cool but as said, highly optional :)
