### ISSUE TITLE
FLIRT added to coreg CT to MRI

### ISSUE THREAD

**Issue by andreashorn** [leaddbs/leaddbs#161]
Hi all, as a request from @adhusch, we added FLIRT as an additional CT coregistration method. Based on their experience in Luxembourg, it works much more robustly for them in comparison to ANTs or BRAINSFit.
Now this also adds complexity to the DiODe tool. @Till-Dembek, could you maybe check whether this works for DiODe?
Happy to discuss on Slack.

https://github.com/leaddbs/leaddbs/blob/89fd00f7fb6926b9319a39bf2181ed3a110d84d2/ea_coregctmri_fsl.m#L1

**Comment by adhusch** [comment]
@adhusch add conversion to ants format using c3d
