### ISSUE TITLE
 normalization error (ea_prefs.m)

### ISSUE THREAD

**Issue by ariannafelice** [leaddbs/leaddbs#162]
Dear all,
i’m trying to recompute the normalization with an other algorithm. When i run i got this error

Error using ea_error (line 16)
IXI database path is specified but the folder cannot be accessed. Please make sure that the absolute path in ea_prefs.m
(prefs.ixi.dir) points to the correct folder containing the IXI database.
Error in ea_getIXI_IDs>ea_convID2cell (line 46)
ea_error(‘IXI database path is specified but the folder cannot be accessed. Please make sure that the absolute path in
ea_prefs.m (prefs.ixi.dir) points to the correct folder containing the IXI database.’);
Error in ea_getIXI_IDs (line 29)
IDs=ea_convID2cell(IDs);
Error in ea_getmagetpeers (line 11)
peerfolders=ea_getIXI_IDs(21,ptage);
Error in ea_normalize_maget_segment (line 17)
peerfolders=ea_getmagetpeers(options);
Error in ea_checkcoreg>recomputebutn_Callback (line 406)
eval([options.normalize.method,'(options)’]); % triggers the normalization function and passes the options struct
to it.
Error in gui_mainfcn (line 95)
feval(varargin{:});
Error in ea_checkcoreg (line 42)
gui_mainfcn(gui_State, varargin{:});
Error in @(hObject,eventdata)ea_checkcoreg(‘recomputebutn_Callback’,hObject,eventdata,guidata(hObject))
Error while evaluating UIControl Callback

I got the same error even if i set the normalizazion for the first time. I have this problem since this morning. Until yesterday everything worked and I did not change anything. Can somebody help me?
Thanks.
Best, Arianna

**Comment by andreashorn** [comment]
Hi Arianna,

the MAGeT Brain normalization method doesn't really work out-of-the-box. If you want to do that (I wouldn't recommend it for general use, it's pretty advanced stuff), have a look at their primer https://github.com/CobraLab/MAGeTbrain first and try to understand what it's really doing. You'd then need peer-reference brains that would need to be normalized with ANTs, as well. The IXI dataset is currently not openly available in the processed form.

But to be honest I think you should try sticking either with ANTs or SPM.
Furthermore, could you please use our official support channels (the forum or even better the Slack channel)? http://www.lead-dbs.org/helpsupport/
This would make it easier for us.

Thanks!
