### ISSUE TITLE
2D Writeout: "Use none" Atlas

### ISSUE THREAD

**Issue by andreashorn** [leaddbs/leaddbs#33]
reported by pDeman, "Use none" seems not to work in 2D-output:

When atlas “use none”:
Generating Atlas table (first run with new atlas only). This may take a while...
Building atlas table...
Error using spm_vol>spm_vol_hdr (line 80)
File "/home/b67-belledone/Desktop/locate_dbs/lead_dbs/atlases/Use none/gm_mask.nii" does not exist.
Error in spm_vol (line 61)
v = spm_vol_hdr(deblank(P(i,:)));
Error in ea_genatlastable (line 282) V=spm_vol([options.earoot,'atlases',filesep,options.atlasset,filesep,'gm_mask.nii']);
Error in ea_add_overlay (line 13) atlases=ea_genatlastable([],options.earoot,options);
Error in ea_writeplanes (line 210) cuts=ea_add_overlay(boundboxmm,cuts,tracor,options);
Error in ea_write (line 12) cuts=ea_writeplanes(options);
Error in ea_manualreconstruction>ea_endfcn (line 161) ea_write(options);
Error in ea_manualreconstruction>ea_keystr (line 184) ea_endfcn;
Error while evaluating figure KeyPressFcn

**Comment by andreashorn** [comment]
Fix did always show no atlas.

**Comment by ningfei** [comment]
will push a new fix soon.
