### ISSUE TITLE
"busy" icon keeps busy occasionally

### ISSUE THREAD

**Issue by ningfei** [leaddbs/leaddbs#56]

**Comment by andreashorn** [comment]
Hi – it keeps busy everytime when running into errors. This is potentially hard to fix?
Would probably need to add an onerror event listener to the spinner if it were an object :)

Best, Andy

**Comment by andreashorn** [comment]
We could potentially use ea_error to notify each active spinner object to go into "error" mode.

**Comment by ningfei** [comment]
Yes. Besides, maybe we can wrap warnings/infos/errors all into a single function.

**Comment by akapp** [comment]
Can also add ea_busyaction('off') to the close function of lead scene
