### ISSUE TITLE
path handle issue in (at least) check normalization

### ISSUE THREAD

**Issue by ningfei** [leaddbs/leaddbs#57]

**Comment by andreashorn** [comment]
Does this apply to filenames that include spaces or other symbols? wouldnt bother solving those.. could be a nightmare. Users should name their folders without commas, spaces or other special characters..

**Comment by ningfei** [comment]
It's not that difficult to solve this if it's just spaces or other symbols. I think we already have a function to do this (designed to handle our atlas/template folders...). But I forget the detail about this issue. Will check it when I have time. But it's true that the folders should be better without commas, spaces or other special characters.
