### ISSUE TITLE
customized ea_prefs.m got overrode during update

### ISSUE THREAD

**Issue by ningfei** [leaddbs/leaddbs#58]

**Comment by andreashorn** [comment]
We should probably move the ea_prefs file into the users home directory (probably best using a . to hide it and add a "open prefs file" entry to the Lead Tools menu so users can access and edit it within ML).
Storing the ea_prefs not inside the lead-dbs folder has also the advantage that multiple users can use the same lead-dbs installation e.g. on a cluster but still have their own preferences.

**Comment by andreashorn** [comment]
(initially move ea_prefs.m into user directory if no .ea_prefs.m file is present inside user directory already and delete ea_prefs.m from lead dir if present in user directory.

**Comment by andreashorn** [comment]
The only problem arises if we add new entries to the prefs file. should append new entries as new lines using ea_gencode to the .ea_prefs.m file in the user's home.

**Comment by plettigp** [comment]
Maybe we should keep a master file in the lead directory and look for a user specific Version(maybe ea_prefs_user (like sublime text)) in which only the entrys different from the master are stored. Then we could update the Master and add new options without overriding anything

**Comment by andreashorn** [comment]
Last commit fixed this.
