### ISSUE TITLE
Dicom import only SPM8

### ISSUE THREAD

**Issue by plettigp** [leaddbs/leaddbs#61]
When I'm using SPM12 for import, it will only unzip and rename the files and it creates a new folder in the "output" directory but does not copy the files over to their new location.

**Comment by andreashorn** [comment]
DCM2Nii is already installed (by Ningfei) we should totally skip the SPM DICOM import and only use DCM2nii. but somebody needs to implement this..

**Comment by ningfei** [comment]
So far just import manually, will incorporate dci2nii later when I have time.
#59
