### ISSUE TITLE
Auto-find path to xelatex?

### ISSUE THREAD

**Issue by andreashorn** [leaddbs/leaddbs#66]
For now, the path to xelatex (latex2pdf engine) needs to be specified manually within ea_prefs for the PDF export to work. Maybe we can even include xelatex inside Lead-DBS or auto-find the path of the xelatex binary on the system?

On my mac if I enter in terminal
which xelatex
/Library/TeX/texbin/xelatex

if I enter in ML:
! which xelatex
not found..

**Comment by andreashorn** [comment]
@ningfei I assigned you here since you might be the only person who has a clue on how to do this.
If it's too complicated, I'd think we should just close this issue for now and users need to install Latex manually (and set the path in ea_prefs).

**Comment by ningfei** [comment]
1. It's not realistic to add the latex binaries inside lead-dbs. Latex is a complex system with a lot of packages. They are strongly bundled. It's not easy or worth doing this. The user should rather have their own latex system correctly installed (for example, on linux: texlive, on win: MikTeX, on mac: MacTeX).

2. Once Latex is correctly installed, the corresponding environment variables or symbol links will be created. If you can call `xelatex` command from terminal, you should be able to call it from matlab using `system('xelatex')`. If not, you need to check the environment variables or symbol links to make it work. The easiest way would be soft linking `xelatex` to `/usr/bin/` or `/usr/local/bin/` I guess.

3. We can add a warning (with useful links) there if `system('which xelatex')` return `not found`, telling the user they need Latex installed to create the PDF. The links can point to Latex pages/wikis.
