### ISSUE TITLE
Using FNIRT to segment in native space

### ISSUE THREAD

**Issue by siobhane** [leaddbs/leaddbs#81]
When selecting a subject for segmentation in native space using FNIRT, I sometimes get this error and Matlab aborts:
![screen shot 2016-11-27 at 17 21 00](https://cloud.githubusercontent.com/assets/15309848/20652379/056c738a-b4c6-11e6-8569-2218e7c68329.png)

**Comment by ningfei** [comment]
First check you `anat.nii` image to see if it's really there and if it's corrupt for some reasons. Then follow the instruction below and check the output to see if there's still problem:

0.  Copy `bet2.maci64` and the  `anat.nii` file in the attached [anat.zip](https://github.com/leaddbs/leaddbs/files/615606/anat.zip) to your desktop
1. Open `Terminal` (via mac `Spotlight`)
2. type `cd ~/Desktop` in terminal, then `Enter`
3. type `chmod 755 bet2.maci64` in terminal, then `Enter`
4. type `export FSLOUTPUTTYPE=NIFTI`, then `Enter`
5. type `./bet2.maci64 anat.nii out.nii --verbose -m`, , then `Enter`  

Check if it works. If it works well, copy your `anat.nii` (suppose it's not corrupt) to `Desktop`, try the above `5th` step again.  If there's still the same error reated to `libc++abi.dylib`, please paste the output of the following commands:

1. `sw-vers -productVersion`
2. `ls /usr/lib/libstdc++*`

**Comment by ningfei** [comment]
Bug of FSL `bet2` (only the one from neurodebian works, all other binaries fail with segment fault)
