### ISSUE TITLE
Problems with DARTEL - 'Warning: No anatomy information found.'

### ISSUE THREAD

**Issue by siobhane** [leaddbs/leaddbs#82]
When I try to use DARTEL for normalization and segmentation in native space I constantly get this error message, although there are three anatomy files in the subject's folder: anat.nii, anat_t1.nii and anat_pd.nii. None of the files are corrupted.
![screen shot 2016-11-29 at 09 36 15](https://cloud.githubusercontent.com/assets/15309848/20713749/7ff2c698-b617-11e6-993e-e7ae4bf384f5.png)

**Comment by ningfei** [comment]
It's a warning (no harm) not an error, and is already fixed.
