### ISSUE TITLE
Bug in native 3d render with atlas set to 'Use none'

### ISSUE THREAD

**Issue by akapp** [leaddbs/leaddbs#94]
When running "Render 3D" and choosing "Use none" in  "Native space" I get the following error:

```
Error in ea_ptspecific_atl (line 3)
if strcmp(options.atlasset(1:13),'Local atlas: ') % manually installed atlas
coded with this prefix by lead-dbs.

Error in ea_autocoord (line 109)
        ea_ptspecific_atl(options);

Error in ea_run (line 89)
                    ea_autocoord(options);

Error in lead_dbs>run_button_Callback (line 219)
ea_run('run',options);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in lead_dbs (line 43)
    gui_mainfcn(gui_State, varargin{:});
````

It seems to me that options.atl.genpt should be equal to 0 when choosing "Use none" so that there is no call to ea_ptspecific_atl in this case, but it's not. Changing options.at.genpt from 1 to 0  doesn't completely fix the problem though, because there is another error in ea_write at line 18 when options.atlasset='Use none'

```
Error in ea_write (line 18)
strcmp(options.atlasset(1:13),'Local atlas: ')
Index exceeds matrix dimensions
```

so I added the following:

```
elseif length(options.atlasset)>=13 && strcmp(options.atlasset(1:13),'Local atlas: ')
       options.atlasset=options.atlasset(14:end);
   
   elseif strcmp(options.atlasset,'Use none')
       % do nothing
   end
```

A bit verbose, but I added the second elseif for clarity. Feel free to condense. 

Still need to update ea_handles2options so that options.atl.genpt is 0 when "Use none" is selected. Interestingly, this doesn't happen in MNI space (options.atl.genpt=0). Probably an easy fix...?

**Comment by andreashorn** [comment]
Hi @akapp, thanks for the fix.
It's true that the atlas selection is a bit too verbose in general (as is the patient select box), will need to find a better solution sooner or later.

**Comment by akapp** [comment]
Still need to update ea_handles2options. Will get back to you soon

**Comment by akapp** [comment]
Fixed
