### ISSUE TITLE
Axis bug in Native Space 3d viewer

### ISSUE THREAD

**Issue by akapp** [leaddbs/leaddbs#95]
There's a bug in the axis settings for the 3D viewer in native space.

In ea_anatomycontrol.m (lines 383 to 409) the axis is hardcoded. 

For example I have an image that requires axis scales [-200 200 -50 250 -100 150], but the '3d' toggle sets the axis to [-100 100 -130 100 -70 100] causing some of my image to get cut out.

I see you've used handles.xval, yval etc. for some the x/y/z cuts but even still some of the other axis values are off in different cases.

Can we generalize these lines to accomodate different file dimensions?

**Comment by andreashorn** [comment]
Hi @akapp very happy if you want to fix/adjust the native viewer a bit. Unfortunately I barely ever use the native view these days so never come across these issues. Let me know if I can help.

**Comment by akapp** [comment]
Sounds good @andreashorn. Thanks for getting back to me so fast. 

It looks like the axis is optimized for a 394x466x378 image like the mni_hires images. I'll make sure to only adjust the axis in the native viewer.
